# -*- coding: utf-8 -*-
"""MindMate,ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1keG46pJlGbeRKfijNk368uFLEDx7kpQ-
"""

import time
import random

# Dictionary of emotional support content
motivational_quotes = [
    "Keep going. Everything you need will come to you at the perfect time.",
    "You’re doing better than you think.",
    "One step at a time is still progress.",
    "Your mental health is just as important as your physical health."
]

breathing_exercise = """
Let's try a simple breathing exercise:
- Inhale deeply for 4 seconds...
- Hold your breath for 4 seconds...
- Exhale slowly for 6 seconds...
Repeat this for 3 cycles. Ready? Breathe with me...
"""

virtual_walks = [
    "You are walking through a quiet forest. Birds are chirping, and the air is fresh.",
    "Imagine you're by the beach. You hear waves crashing gently as the sun warms your face.",
    "You're walking in a peaceful garden full of blooming flowers. You feel calm and relaxed."
]

# Function to greet the user
def greet_user():
    print("🧠 Welcome to MindMate - Your Virtual Mental Health Companion 🧠")
    print("---------------------------------------------------------------")
    name = input("What’s your name? ")
    print(f"Hi {name}, I'm here to help you feel a little better today. 💬")
    return name

# Function to get user's current mood
def get_mood():
    print("\nHow are you feeling today?")
    print("1. Sad 😢")
    print("2. Anxious 😰")
    print("3. Stressed 😓")
    print("4. Happy 🙂")
    mood = input("Enter the number that best describes your mood: ")
    return mood

# Function to respond based on mood
def respond_to_mood(mood):
    print("\nProcessing your response...\n")
    time.sleep(1.5)

    if mood == "1":
        print("I'm sorry you're feeling sad. Here's a quote that might help:\n")
        print(random.choice(motivational_quotes))
    elif mood == "2":
        print("Anxiety can be overwhelming. Let's do a short breathing exercise:\n")
        print(breathing_exercise)
    elif mood == "3":
        print("Stress can weigh us down. Let’s take a short virtual walk in your mind:\n")
        print(random.choice(virtual_walks))
    elif mood == "4":
        print("That's wonderful! Here's something to keep that positivity going:\n")
        print(random.choice(motivational_quotes))
    else:
        print("I didn’t understand that, but I’m still here for you. Let’s take a deep breath together.")

# Main program loop
def main():
    user_name = greet_user()
    continue_chat = True

    while continue_chat:
        mood = get_mood()
        respond_to_mood(mood)

        again = input("\nWould you like to talk again? (yes/no): ").lower()
        if again != "yes":
            continue_chat = False
            print(f"\nThank you for visiting, {user_name}. Take care of yourself. 💚")

# Run the program
if __name__ == "__main__":
    main()